name       : pz7ip
version    : 9.38.1
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/p7zip/p7zip/9.38.1/p7zip_9.38.1_src_all.tar.bz2 : fd5019109c9a1bf34ad3257d37a6853eae8151ff50345f0a3ffba7d8c5fdb995
license    : LGPL-2.1+
summary    : 7-Zip
builddeps  :
    - yasm
description: |
    7-Zip is a file archiver with a high compression ratio.
build      : |
    cp makefile.linux_clang_amd64_asm makefile.machine
    %make all3 OPTFLAGS="$CFLAGS"
install    : |
    %make_install DEST_DIR="$installdir" DEST_HOME=/usr DEST_MAN=/usr/share/man DEST_SHARE="%libdir%/p7zip"
