name       : p7zip
version    : '17.05'
release    : 13
source     :
    - https://github.com/p7zip-project/p7zip/archive/refs/tags/v17.05.tar.gz : d2788f892571058c08d27095c22154579dfefb807ebe357d145ab2ddddefb1a6
homepage   : https://github.com/p7zip-project/p7zip
license    : LGPL-2.1-or-later
component  : system.utils
summary    : p7zip is a port of 7za for POSIX systems like Unix
description: |
    p7zip is a port of 7za for POSIX systems like Unix
optimize   : speed
builddeps  :
    - yasm
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-Use-system-locale-to-select-OEM-code-page-for.patch
build      : |
    %make OPTFLAGS="$CPPFLAGS $CFLAGS" 7z 7zr 7za
install    : |
    %make_install DEST_DIR="$installdir" DEST_HOME=/usr DEST_MAN=/usr/share/man DEST_SHARE="%libdir%/p7zip"
    rm -rf $installdir/usr/share/doc
profile    : |
    %make test
check      : |
    %make test
