name       : p7zip
version    : '16.02'
release    : 10
source     :
    - https://jaist.dl.sourceforge.net/project/p7zip/p7zip/16.02/p7zip_16.02_src_all.tar.bz2 : 5eb20ac0e2944f6cb9c2d51dd6c4518941c185347d4089ea89087ffdd6e2341f
license    : LGPL-2.1
component  : system.utils
summary    : 7-Zip
builddeps  :
    - yasm
optimize   : speed
description: |
    7-Zip is a file archiver with a high compression ratio.
build      : |
    %patch -p1 < $pkgfiles/security/CVE-2016-9296.patch
    %patch -p1 < $pkgfiles/security/CVE-2017-17969.patch
    %patch -p1 < $pkgfiles/security/CVE-2018-5996.patch
    %patch -p1 < $pkgfiles/security/CVE-2018-10115.patch
    cp makefile.linux_amd64_asm makefile.machine
    %make all3 OPTFLAGS="$CFLAGS"
install    : |
    %make_install DEST_DIR="$installdir" DEST_HOME=/usr DEST_MAN=/usr/share/man DEST_SHARE="%libdir%/p7zip"
profile    : |
    %make test
check      : |
    %make test
